language: python

python:
  - "2.7"

before_install:
  - cd test
  - git clone https://github.com/lh3/bwa.git
  - cd bwa
  - git checkout tags/0.7.9a
  - make
  - cd ..
  - PATH=`pwd`/bwa:$PATH
  - git clone https://github.com/arq5x/bedtools2.git
  - cd bedtools2
  - git checkout tags/v2.28.0
  - make
  - cd ..
  - PATH=`pwd`/bedtools2/bin:$PATH
  - cd ..

install: 
  - pip install -r requirements.txt && pip freeze

script:
  cd test && nosetests --exe -v

notifications:
  email:
    recipients:
      - lukas.heumos@posteo.net
    on_success: never 
    on_failure: always